
services:
  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: llm-chat-dev
    network_mode: host  # Using host network instead of port mapping
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host --strictPort

  # Production service
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-chat-prod
    network_mode: host  # Using host network instead of port mapping
    restart: unless-stopped
